export const API_ERROR = "API_ERROR";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const USER_DOES_NOT_EXISTS = "USER_DOES_NOT_EXISTS";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
export const RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS";
export const RESOURCE_DOES_NOT_EXISTS = "RESOURCE_DOES_NOT_EXISTS";
export const PROJECT_ALREADY_EXISTS = "PROJECT_ALREADY_EXISTS";
export const PROJECT_DOES_NOT_EXISTS = "PROJECT_DOES_NOT_EXISTS";
export const UNKNOWN_RESOURCE_TYPE = "UNKNOWN_RESOURCE_TYPE";
export const PROJECT_INITIALIZATION_ERROR = "PROJECT_INITIALIZATION_ERROR";
export const PLATFORM_ERROR = "PLATFORM_ERROR";
export const OPEN_SHIFT_ERROR = "OPEN_SHIFT_ERROR";
export const ASSEMBLY_DOES_NOT_EXISTS = "ASSEMBLY_DOES_NOT_EXISTS";
export const BUILD_FAILED = "BUILD_FAILED";
export const GRADLE_BUILD_ERROR = "GRADLE_BUILD_ERROR";
export const LOG_DOES_NOT_EXISTS = "LOG_DOES_NOT_EXISTS";
export const MODULE_DOES_NOT_EXISTS = "MODULE_DOES_NOT_EXISTS";
export const MODULE_ALREADY_EXISTS = "MODULE_ALREADY_EXISTS";
export const FILE_DOES_NOT_EXISTS = "FILE_DOES_NOT_EXISTS";
export const INSTALLATION_FAILED = "INSTALLATION_FAILED";
export const UPDATING_FAILED = "UPDATING_FAILED";
export const STOPPING_FAILED = "SOPPING_FAILED";
export const DELETING_FAILED = "DELETING_FAILED";

export const KNOWN_ERROR_CODES = [
    UNAUTHORIZED,
    USER_DOES_NOT_EXISTS,
    INVALID_PASSWORD,
];
