export const MODULE_MIN_COUNT = 1;
export const MODULE_MAX_COUNT = 10;
export const MAX_MODULES_FILE_COUNT = 5;
export const MAX_MODULES_FILE_SIZE_BYTES = 20 * 1024;
export const MAX_MODULES_FILE_SIZE_MESSAGE = "200кб";
export const MAX_MODULE_NAME_SIZE = 63;
export const MODULE_CONFIGURATION_EDITOR_HEIGHT = 250
export const MODULE_APPLICATION_CONFIGURATION_EDITOR_HEIGHT = 250
