export const PROJECT_CREATED_STATE = "PROJECT_CREATED";
export const PROJECT_INITIALIZED_STATE = "PROJECT_INITIALIZED";
export const PROJECT_INITIALIZATION_FAILED_STATE = "PROJECT_INITIALIZATION_FAILED";
export const PROJECT_RELOAD_STARTED_STATE = "PROJECT_REFRESH_STARTED";
export const PROJECT_RELOADING_STATE = "PROJECT_RELOADING";

export const ASSEMBLY_STARTED_STATE = "ASSEMBLY_STARTED";
export const ASSEMBLY_DONE_STATE = "ASSEMBLY_DONE";
export const ASSEMBLY_FAILED_STATE = "ASSEMBLY_FAILED";
export const ASSEMBLY_CANCELED_STATE = "ASSEMBLY_CANCELED";
export const ASSEMBLY_STARTED_ON_RESOURCE_STATE = "ASSEMBLY_STARTED_ON_RESOURCE";
export const ASSEMBLY_BUILDING_STATE = "ASSEMBLY_BUILDING";
export const ASSEMBLY_RESTARTED_STATE = "ASSEMBLY_RESTARTED";

export const MODULE_INSTALLING_STATE = "MODULE_INSTALLING";
export const MODULE_INSTALLATION_STARTED_STATE = "MODULE_INSTALLATION_STARTED";

export const MODULE_UPDATE_STARTED_STATE = "MODULE_UPDATE_STARTED";
export const MODULE_STOP_STARTED_STATE = "MODULE_STOP_STARTED";
export const MODULE_RESTART_STARTED_STATE = "MODULE_RESTART_STARTED";
export const MODULE_UNINSTALL_STARTED_STATE = "MODULE_UNINSTALL_STARTED";
export const MODULE_UPDATING_STATE = "MODULE_UPDATING";
export const MODULE_STOPPING_STATE = "MODULE_STOPPING";
export const MODULE_RESTARTING_STATE = "MODULE_RESTARTING";
export const MODULE_UNINSTALLING_STATE = "MODULE_UNINSTALLING";

export const MODULE_NOT_INSTALLED_STATE = "MODULE_NOT_INSTALLED";
export const MODULE_INVALID_STATE = "MODULE_INVALID";
export const MODULE_RUN_STATE = "MODULE_RUN";
export const MODULE_STOPPED_STATE = "MODULE_STOPPED";

export const LOAD_TEST_STARTED_STATE = "LOAD_TEST_STARTED";
export const LOAD_TEST_DONE_STATE = "LOAD_TEST_DONE";
export const LOAD_TEST_FAILED_STATE = "LOAD_TEST_FAILED";
export const LOAD_TEST_CANCELED_STATE = "LOAD_TEST_CANCELED";
export const LOAD_TEST_STARTED_ON_RESOURCE_STATE = "LOAD_TEST_STARTED_ON_RESOURCE";
export const LOAD_TEST_RUNNING_STATE = "LOAD_TEST_RUNNING";
