export const OPEN_SHIFT_RESOURCE = "OPEN_SHIFT_RESOURCE";
export const ARTIFACTS_RESOURCE = "ARTIFACTS_RESOURCE";
export const GIT_RESOURCE = "GIT_RESOURCE";
export const PLATFORM_RESOURCE = "PLATFORM_RESOURCE";
export const PROXY_RESOURCE = "PROXY_RESOURCE";

export const EXECUTORS = [OPEN_SHIFT_RESOURCE]

export const REGISTRIES = [OPEN_SHIFT_RESOURCE, ARTIFACTS_RESOURCE]

export const PROXIES = [PROXY_RESOURCE]

export const ALL_RESOURCES = [ARTIFACTS_RESOURCE, OPEN_SHIFT_RESOURCE, GIT_RESOURCE, PLATFORM_RESOURCE, PROXY_RESOURCE];
